language: ruby
rvm:
  - 2.4

script: jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

sudo: false

cache: bundler # caching bundler gem packages will speed up build
