title: Learn X in Y Minutes (Language Edition)
email: boka.wayne@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is an offshoot of the Learn X in Y Minutes project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wtboka
github_username: wboka

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
# theme: minima
plugins:
  - jekyll-feed
repository: wboka/learnxinyminutes-language-edition

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
